server:
  port: 8080
spring:
  application:
    name: FitMode
  datasource:
    url: jdbc:postgresql://localhost:5432/fitmode
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true